/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSponsorsRouteImport } from './routes/_app/sponsors'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppReceiptsRouteImport } from './routes/_app/receipts'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppFollowUpRouteImport } from './routes/_app/follow-up'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminsRouteImport } from './routes/_app/admins'
import { Route as AppChildrenIndexRouteImport } from './routes/_app/children/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppChildrenIdRouteImport } from './routes/_app/children/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSponsorsRoute = AppSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpRoute = AppFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminsRoute = AppAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenIndexRoute = AppChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChildrenIdRoute = AppChildrenIdRouteImport.update({
  id: '/children/$id',
  path: '/children/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AppAdminsRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/follow-up': typeof AppFollowUpRoute
  '/payments': typeof AppPaymentsRoute
  '/receipts': typeof AppReceiptsRoute
  '/reports': typeof AppReportsRoute
  '/sponsors': typeof AppSponsorsRoute
  '/children/$id': typeof AppChildrenIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/children/': typeof AppChildrenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AppAdminsRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/follow-up': typeof AppFollowUpRoute
  '/payments': typeof AppPaymentsRoute
  '/receipts': typeof AppReceiptsRoute
  '/reports': typeof AppReportsRoute
  '/sponsors': typeof AppSponsorsRoute
  '/children/$id': typeof AppChildrenIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/children': typeof AppChildrenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admins': typeof AppAdminsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/follow-up': typeof AppFollowUpRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/receipts': typeof AppReceiptsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sponsors': typeof AppSponsorsRoute
  '/_app/children/$id': typeof AppChildrenIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_app/children/': typeof AppChildrenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/audit'
    | '/dashboard'
    | '/follow-up'
    | '/payments'
    | '/receipts'
    | '/reports'
    | '/sponsors'
    | '/children/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/children/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admins'
    | '/audit'
    | '/dashboard'
    | '/follow-up'
    | '/payments'
    | '/receipts'
    | '/reports'
    | '/sponsors'
    | '/children/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/children'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admins'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/follow-up'
    | '/_app/payments'
    | '/_app/receipts'
    | '/_app/reports'
    | '/_app/sponsors'
    | '/_app/children/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_app/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sponsors': {
      id: '/_app/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AppSponsorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts': {
      id: '/_app/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-up': {
      id: '/_app/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AppFollowUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admins': {
      id: '/_app/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AppAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/': {
      id: '/_app/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof AppChildrenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/children/$id': {
      id: '/_app/children/$id'
      path: '/children/$id'
      fullPath: '/children/$id'
      preLoaderRoute: typeof AppChildrenIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminsRoute: typeof AppAdminsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFollowUpRoute: typeof AppFollowUpRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSponsorsRoute: typeof AppSponsorsRoute
  AppChildrenIdRoute: typeof AppChildrenIdRoute
  AppChildrenIndexRoute: typeof AppChildrenIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminsRoute: AppAdminsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFollowUpRoute: AppFollowUpRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSponsorsRoute: AppSponsorsRoute,
  AppChildrenIdRoute: AppChildrenIdRoute,
  AppChildrenIndexRoute: AppChildrenIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
